version: '3.4'
services:
    notes-app:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: ./.env
        labels:
            kompose.service.type: LoadBalancer
        ports:
            - '8080:3000'
