version: '3'
services:
    api-service:
        build:
            context: ./api-service
            dockerfile: Dockerfile
        container_name: 'api-service'
        env_file: ./api-service/.env.e2e
        environment:
            - DOCKER_BUILD=true
        networks:
            internal-network:
                aliases:
                    - api-service

    ui-service:
        build:
            context: ./ui-service
            dockerfile: Dockerfile
        container_name: 'ui-service'
        env_file: ./ui-service/.env.e2e
        environment:
            - DOCKER_BUILD=true
            - API_URL=http://api-service:3001
        ports:
            - '3000:3000'
        networks:
            internal-network:
                aliases:
                    - ui-service

    selenium-hub:
        image: selenium/hub:3.141.59
        container_name: selenium-hub
        ports:
            - '4444:4444'
        networks:
            internal-network:
                aliases:
                    - selenium-hub
    chrome:
        image: selenium/node-chrome:3.141.59
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
        networks:
            internal-network:
                aliases:
                    - chrome

    nightwatch:
        build:
            context: ./e2e
            dockerfile: Dockerfile
        depends_on:
            - selenium-hub
            - ui-service
        environment:
            - SELENIUM_HUB_URL=http://selenium-hub:4444
        volumes:
            - ./e2e:/home/nightwatch
        networks:
            internal-network:
                aliases:
                    - nightwatch

networks:
    internal-network:
        driver: bridge
