version: '3'
services:
    api-service:
        build: 
            context: ./api-service
            dockerfile: Dockerfile
        container_name: "api-service"
        env_file: ./api-service/.env
        environment:
            - DOCKER_BUILD=true
        networks:
            internal-network:
                aliases:
                    - api-service

    ui-service:
        build: 
            context: ./ui-service
            dockerfile: Dockerfile
        container_name: "ui-service"
        env_file: ./ui-service/.env
        environment:
            - DOCKER_BUILD=true
            - API_URL=http://api-service:3001
        networks:
            internal-network:
                aliases:
                    - ui-service

    chromedriver:
        image: blueimp/chromedriver
        environment:
            - VNC_ENABLED=true
            - EXPOSE_X11=true
        ports:
            - 5900:5900
        networks:
            internal-network:
                aliases:
                    - chromedriver
    nightwatch:
        image: blueimp/nightwatch:0.9
        # init: true
        depends_on:
            - chromedriver
            - ui-service
        environment:
            - WAIT_FOR_HOSTS=ui-service:3000 chromedriver:4444 chromedriver:6060
        volumes:
            - ./e2e:/home/node
        networks:
            internal-network:
                aliases:
                    - nightwatch

networks:
    internal-network:
        driver: bridge
