version: '3'
services:
    api-service:
        build:
            context: ../api-service
            dockerfile: Dockerfile
        image: arturjs/notes-app_api-service:0.0.2
        container_name: 'api-service'
        env_file: ../api-service/.env
        environment:
            - DOCKER_BUILD=true
        labels: 
            kompose.service.expose: 'api-service'
        ports:
            - "3001:3001"
        networks:
            internal-network:
                aliases:
                    - api-service

    ui-service:
        build:
            context: ../ui-service
            dockerfile: Dockerfile
        image: arturjs/notes-app_ui-service:0.0.2
        container_name: 'ui-service'
        env_file: ../ui-service/.env
        environment:
            - DOCKER_BUILD=true
            - API_URL=http://api-service:3001
        labels:
            kompose.service.type: LoadBalancer
        ports:
            - "8080:3000"
        networks:
            internal-network:
                aliases:
                    - ui-service

networks:
    internal-network:
        driver: bridge
