apiVersion: ENC[AES256_GCM,data:STo=,iv:u1V4Gar9MYvYK+Psoy5s6qXQ65hQ3UqYt1LxkJMr9oA=,tag:2YfvG2Fb2op/PREWRPTVOQ==,type:str]
data:
    HOST: ENC[AES256_GCM,data:3gHitKoPgRcMMF4=,iv:MPgFRENetX/1IWjIJiQeSWCTXlzu8kPp7SsVubtwaDg=,tag:TmjlAh0BrsOUOpLwvQVB8A==,type:str]
    PORT: ENC[AES256_GCM,data:9oeKfg==,iv:my4NezU6CeFl5Rs+QyXVNwcCqT5VXCmp+lJHsnb/5Os=,tag:Ms34cC+ulV2h2pUpyDCZjg==,type:str]
    AUTH_SESSION_SECRET: ENC[AES256_GCM,data:mwZ0TfVMadifY+Pb8z8=,iv:KGHH5f4X/goST/UxiMD9lTzUIkphbyw67a4e4tj/wMA=,tag:ysd70Pl4fF/Ci+H485+bqg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:7DtdfVec9iWDb0tQ+7bAKktCaN14RC0YhLVy5/HtYvuZQYaSqAFQlu5N7TBbMXzH5UGdVXqczsqkCSglurgIVABMKYsFHR7P0yF3q6ucRGzTul03v2qYPeMywGKunLua,iv:i2q/KnNAD/5sTefcsjqS4IT09Yauw81XNZBuo6VH0K0=,tag:B9UxVobMAv3IsWxQDjaU8Q==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:E1vcUs0kcIfTDg==,iv:Y025SkY3E5hrq0fKobmNJ4YmWyXVSs0A7yWOewfMh/A=,tag:w9kj8obexvcYQzZEHWMsIw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:rhac9Q==,iv:Vx3L8spGIVAEsxGg2DWXTEdiYXf0Xk0ShblJ5DUW7sE=,tag:a/CztVCo8cHKYXsjUDw9Hg==,type:str]
    DROPBOX_TOKEN: ENC[AES256_GCM,data:dmAN5HbqmC1jvyp+WAwed57i7jqsBdoaEeo1xMLXUG3C2fPdf6eQ5ZxH+mHXvK4v2aR+Q1exNsLXubXGY2qMtg==,iv:9govxdrlilC2R5NadfV1hJSLBXuQmwSW/+PMfKkZ9yI=,tag:/tHrH0BHk6CEQIXByNQXjA==,type:str]
    MAIL_USER_SERVICE: ENC[AES256_GCM,data:J+1sRzCc,iv:YhpXa1TYd83P32KNK+qcugWljC/xF7deNAY3ppRbAnc=,tag:9AZlcAPNJpmBlLpL8UOdTw==,type:str]
    MAIL_USER_EMAIL: ENC[AES256_GCM,data:e6zsvc6hmO1rVFo96885qy+Q/Q==,iv:SmBb6kIlw35Zq75a1uiv2xEBElYSZH+ungg0EXEiiYU=,tag:OroACmNp1VV973LqqENEVw==,type:str]
    MAIL_USER_PASSWORD: ENC[AES256_GCM,data:RbCnEd8VHhRT8w3v2tuw6bI3tgZy,iv:1ESlAR/HKYhYibqKmG/wyOJC+ZQDPk+MEyn1ey58h9c=,tag:0oHvl69KfvBABk70nL/fJQ==,type:str]
kind: ENC[AES256_GCM,data:jlCHWmyYbNg+,iv:dBZOL3/OIjiO/a4+02CeD7/guWDLpHA9NVx5eJUZ6PA=,tag:ee1/YFVMTrNz6VGcu5dbRA==,type:str]
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: ENC[AES256_GCM,data:uOKdrQqVBpKoedcXteRPlXhrBWHHN9pWPkTB0g==,iv:Bk7pz5YLYwmdkZs8yJS+HK9ejLfBlqQ7gkz830kUN3k=,tag:AAFWA3Q+0W/ETjjuHQPb5g==,type:str]
    name: ENC[AES256_GCM,data:snDjXVG8d8ZJQ8EN+K5gmG8TiebbzDu5IAysRw==,iv:ypHXf0M+82zwe7CC83VrgkkCsmmVlOteczWZIDgxXmY=,tag:4Y4ba1Y6Y9/oFfqBK9EvWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-05-09T17:48:40Z'
    mac: ENC[AES256_GCM,data:/EHUeWtY63hojCQSxJF9zDspOnsqe5PTZ3lVNYW47IRcAlFolRHivAANBvZ7D5m0W1zsXKKFCLSwRG4FZIjd7TL0o/1arASBd0mQyGs3kDCkEntn8YKpdl5qGH35V5vyWKT8B5vbgYOyjn+uMW4l0f6O1EkDgyDh6PoiMHvuGJM=,iv:IvYZ+Ds2lOGtnbwxEz+85YkFnuCVscGpEbo42kATNq8=,tag:ScSrdHmEnNjZbR5eWEh0lg==,type:str]
    pgp:
    -   created_at: '2019-05-09T17:48:38Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyTjj+Lt7TXNAQv/Xr9iI+YeXs5s7+XuS1zqx53QqKBNePN6RDwDbgeIMa1w
            SJmrijW7JCHbK2wwkl2CKxYnOM1j8rU4Dtd1UiY/sbYUnVlehs03IeXO/JxCAZkr
            C/imYGClqYeZTMXOi9YGb+3fEl1+VjGmU575JmupVx3stsjCxIE9W+gM6rp+lw7b
            V1xVuTo1+TFcrgzX5zU7SqIrOffq7B1+BxU17ykMeaXFaTLDP0I9CKGg54fZNmrV
            GYSeLb5IcO+lX9NTK3ERYvqjeoqnqjD4lhv3WIAeShJO0Mvbt0IjihQ1HowS4RlQ
            oRSsiL221yqnl0F+2puz0cFrEInOZXq04cGaH4LpfMG/hYkrE1tpKD66o/yXPDEi
            8V0BcCFbw6kjGPzPpk+gy01cvbN2x/7ahh/DT++IpTx3sI8XZsLhbYqEgBF8qaAi
            +9FW+AVNGOrfc4XZGjSMK6j24ez8uX8duHaePJRltOlFur6zrZVCbHlYNj7rN4ka
            1qmaei5ZXySa9EOe4WJb0l4BiExPdTRl+VH2jh//59ErB/+siXLe9oJ68hqo8DoN
            q74FjPnIiBljOl0fefIw0ZLGW1XAyR2qEqGaJ6kf72HlqHF6rkUWsX8h502l3Y41
            RPv2svcmTCxrjU16KXUn
            =qFTq
            -----END PGP MESSAGE-----
        fp: 7C3F485E547AA67138CAAF71F884969C8E74D0D2
    unencrypted_suffix: _unencrypted
    version: 3.3.0
