apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: api-service
    name: api-service
spec:
    rules:
        - host: api-service
          http:
              paths:
                  - backend:
                        serviceName: api-service
                        servicePort: 3001
status:
    loadBalancer: {}
