apiVersion: ENC[AES256_GCM,data:mMY=,iv:bQjLhpOf+MMaW1/L73cyRiOUSxKtoi9sMOs5EXTjzI8=,tag:pb+J1aCm8vRWaZW2QNto9g==,type:str]
data:
    API_URL: ENC[AES256_GCM,data:wnKV65Nn1ROX+QjVVeOpTR0f5jdgci0=,iv:nXZzKYu+/bmEEOC4jgDVV5TXT3R/Nd5HjmWh+UYcnuo=,tag:0nqGyYIMb0WIL8dEIj0rDA==,type:str]
    AUTH_SESSION_SECRET: ENC[AES256_GCM,data:ECIbD0owaNdekT8+OKc=,iv:IKvUGXOtHVTvkL9ejw5rc3v77l9a8elLYoceav6/x1s=,tag:lSxeffHRNfu3GSEeR7qv0A==,type:str]
    HOST: ENC[AES256_GCM,data:I9fznIqHrjlK,iv:Vz6Ib80OuzMxJbZcMxsDjbpAHAE4kE8syIfXfksB0fg=,tag:v0pez/xeJDkjRq/4U7ZYVg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:hWBR5w==,iv:TmtAjYPp1yvRgyS5QeDyrJnsm1lSfJdqQ1uFfN3X1L4=,tag:s49xLUrCM6V7bSV7YMSBHA==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:SU8xWp6UzoJm5w==,iv:LJdEErwcUSwvfchxJyuXRlD+PkI3PtMznH4qpEHo9jE=,tag:XkTMnVtbmCDynvKsmRVgHQ==,type:str]
    PORT: ENC[AES256_GCM,data:K9+ktw==,iv:BMJn8h1Fsg5djLjpgH1/LXvBxp9cNHxwb+dgHgEHdf4=,tag:e0+JPAbm+Cv/wR+T8KJOiA==,type:str]
kind: ENC[AES256_GCM,data:W/e0p4LWXblZ,iv:vUUBkAz6plDcPUMTDdrd0WJ+6KEDF7AhlicqiiAZng8=,tag:6Z2aNWgkElIB3JRSKQXq9Q==,type:str]
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: ENC[AES256_GCM,data:nTd0ElJ4xFOXnhG5d1eiiTARcMEkxFFHFOQ=,iv:FX5bj8ndKAeP2pzQNMHit+alA6pgbno7Rian7SzS+oY=,tag:dBoPHt/VQ3U/3dmT4zeQ/w==,type:str]
    name: ENC[AES256_GCM,data:nXa4UGD7eDgDDMMJ1NbQinTbam13apvaz8o=,iv:Iwh2XUEyutX5ueNldIzsfpcaGwe7KPpJplgXhJt0Bq8=,tag:jfKv84ji8NHlXV9lwLmeSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-05-08T14:34:01Z'
    mac: ENC[AES256_GCM,data:69xte80FoabSR6UshuEZg22BfSkyQywOfTBBc/WEy3eSzFC9CXL1yyTb2Yut0Sv1vuOKsnvFv1pvlZxtHDS1g76ozvo2oWJa7XijTRoMRU/HgUxTln4VWIm4kD9nlnxsCoflfUMgyoU2Ws892r8Ke8plNH9tQlCyjhVJbUzYXWE=,iv:faYxSQi+nUZWXQ19DlWR+0f7QK9q2e32eQrA2JD6Ly0=,tag:2bmcBMrVa9qg43Vthoj5zQ==,type:str]
    pgp:
    -   created_at: '2019-05-08T14:34:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAyTjj+Lt7TXNAQwArJmy2SpkuahIK8JPUReZCWnhsqO8LB3qnxJMslx1PId/
            mKWJYBDez/5aNOmhC0wce0MicGTfF9orpS5xkmphrgs4HW7YuJTXetkEk+O3D3Bk
            TjZLSGB4H4taoX67wNtTdWCYiUxAydOgnpDi9o/FqUJCjf2gQ8YvPNu+Quxu72kA
            vdSC4aK90/xPg4TN0FtZa7gRjlTT350V0XAGdC0N2j235K4UqcoL792+Ww++gijr
            97GZxbQzAeoygj5Nl+p1SO4fQIxM9vwyxFBbL+MabGQuGj1FeOcX3699OyqjEVc5
            MYs+71I1jT3EZ4azjjPJYbIpNj2NEujMOUYXerJPvKdVxiLg23KesSBPncgKPpGX
            t6ws91TrWWol3uRAEW4UXdF1UIcEfwamV/M1neD2OY45bRyWXGE0x7UhmLeKhC+1
            csdmYk1JEPubMC3bsLpzOYYHUY2assDzHgwDZMQXXbxSUqq4zTGBGk0bHKGNdpOD
            TbYp1iK8kv7sH+kZkCld0l4BzUBxYBaYVtXl674ymBFJKIUzDsMhfL5RfdEeKzYL
            +j9/cyql/QOlvjLAR+CicduLrm7IAGglRu+3cSwJdBasx+f2exZR26IqikWWjVCu
            dzIS7b0WUvTUe836vAbO
            =WCS3
            -----END PGP MESSAGE-----
        fp: 7C3F485E547AA67138CAAF71F884969C8E74D0D2
    unencrypted_suffix: _unencrypted
    version: 3.3.0
