name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - master
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/repos/Notes-App;
            git checkout -f;
            git pull origin master;
            chmod u+x ./scripts/crypto/age.linux.bin;
            export AGE_KEY="${{ secrets.AGE_KEY }}";
            echo "$AGE_KEY" > ./age-key.txt;
            ./scripts/crypto/age.linux.bin -d -i ./age-key.txt .env.age > .env;
            export NVM_DIR="$HOME/.nvm";
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
            nvm install v16.13.1;
            nvm use v16.13.1;
            npm i -g pm2;
            npm install;
            npm run build;
            export PM2_ONLINE_APPS="$(pm2 list | grep online | grep -v pm2)"
            if [[ "$PM2_ONLINE_APPS" != "" ]]; then pm2 reload all; fi
            pm2 stop notes_app 2> /dev/null; # we don't care if notes_app is absent, just stop if it's available
            pm2 start npm --name "notes_app" -- start &
            echo "New version is available on https://$(curl ifconfig.me/ip)/"
